apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
  namespace: talk2wall
data:
  USER_NAME: "root"
  DB_NAME: "talk2wall"
  DB_HOST: "kube-mysql.cvqmi8c8getk.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  EXPIRATION_TIME: "7200000"