grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 3d
    scrapeInterval: 60s
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
      limits:
        memory: 800Mi

prometheusOperator:
  resources:
    requests:
      memory: 64Mi
      cpu: 20m
    limits:
      memory: 128Mi

kube-state-metrics:
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 128Mi

nodeExporter:
  enabled: true

prometheus-node-exporter:
  resources:
    requests:
      memory: 32Mi
    limits:
      memory: 64Mi

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false