apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wnsgh7368/talk2wall-manifest
    targetRevision: main
    path: manifest/backend/chart
    helm:
      valueFiles:
        - values.yaml
        - values-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: talk2wall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true